### ISSUE TITLE
Reader DC.ps1

### ISSUE THREAD

**Issue by Hellements** [farag2/Adobe-Acrobat-DC-Setup#1]
Hello @farag2 . Hope you are doing well.
So I'm having a problem with the Reader DC.ps1 script as you can see on the picture.
![error](https://user-images.githubusercontent.com/88634350/131207224-74665da1-44e8-4c90-b6f9-3dc0a6935473.jpg)
It's a fresh installation of Win10Pro (original) with all latest updates installed and latest Reader x64 installed manually.
Thank you so much.

**Comment by farag2** [comment]
Hi! The rev keys had to be created after the first Acrobat start. Did you launch it before running?

**Comment by Hellements** [comment]
Yes @farag2 , I did launch Acrobat Reader twice and even rebooted the pc and always get that same issue shown on pic above.

**Comment by farag2** [comment]
We need more tests then)

**Comment by farag2** [comment]
Doing tests...

**Comment by farag2** [comment]
Run

```powershell
Get-Package -Name "Adobe Acrobat DC (64-bit)" -ProviderName msi
```

I forgot that `Acrobat Pro` and `Reader x64` are use physically the same engine. Update both scripts. So use this one for `Reader x64` <https://github.com/farag2/Adobe-Acrobat-DC-Setup/blob/master/Adobe_Acrobat_Pro_DC.ps1>. Differences are in the installed services only.
