### ISSUE TITLE
Cannot open AdobeARMservice service on computer

### ISSUE THREAD

**Issue by Patatone** [farag2/Adobe-Acrobat-DC-Setup#2]
I got this error:

`Stop-Service : Service 'Adobe Acrobat Update Service (AdobeARMservice)' cannot be stopped due to the following error:
Cannot open AdobeARMservice service on computer '.'.
At C:\Users\marsl\Documents\Adobe-Acrobat-DC-Setup\Adobe_Acrobat_Reader_Pro_DC.ps1:4 char:37
+ Get-Service -Name AdobeARMservice | Stop-Service -Force
+                                     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Stop-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.StopServiceCommand

`

**Comment by farag2** [comment]
Hi. This is not a problem. You just have no this service. I'll edit the code a little bit to suppress the error.

https://github.com/farag2/Adobe-Acrobat-DC-Setup/blob/699b6eef7cd9278e398689fb59cdd87a7958a878/Adobe_Acrobat_Reader_Pro_DC.ps1#L4
